export const USER_LOGOUT = "USER:LOGOUT";

export const GET_CURRENT_USER = "GET:CURRENT:USER";
export const FETCH_CURRENT_USER = "FETCH:CURRENT:USER";

export const REMOVE_CURRENT_USER = "REMOVE:CURRENT:USER";
