export const SEARCH_UPDATE = "SEARCH:UPDATE";

export const SEARCH_SUBMIT = "SEARCH:SUBMIT";

export const PROPERTY_FETCH = "PROPERTY:FETCH";
export const PROPERTY_FETCH_ERROR = "PROPERTY:FETCH:ERROR";

export const SEARCH_PROPERTY = "SEARCH:PROPERTY";
export const PROPERTY_SINGLE_FETCH = "PROPERTY:SINGLE:FETCH";

export const BOOK_PROPERTY = "BOOK:PROPERTY";
export const BOOK_PROPERTY_SUCCESS = "BOOK:PROPERTY:SUCCESS";
export const BOOK_PROPERTY_FAILURE = "BOOK:PROPERTY:FAILURE";
