export const LOGIN_SUBMIT = "LOGIN:SUBMIT";

export const LOGIN_SUCCESS = "LOGIN:SUCCESS";
export const LOGIN_FAILURE = "LOGIN:FAILURE";

export const LOGOUT_SUBMIT = "LOGOUT:SUBMIT";
export const LOGOUT_SUCCESS = "LOGOUT:SUCCESS";
